name: increment_button
description: Slide the button to change value.
version: 0.0.3
homepage: https://github.com/bradintheusa/increment_button

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter